;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        electric-pair-delete-pair
        end-of-visual-line
        forward-sexp
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        kill-sexp
        my/python-yank
        org-self-insert-command
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-forward-up
        paredit-kill
        paredit-meta-doublequote
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        paredit-splice-sexp
        paredit-wrap-round
        smarter-move-beginning-of-line
        sp-backward-delete-char
        sp-delete-char
        tab-to-tab-stop
        transpose-words
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        describe-key
        eval-last-sexp
        ivy-wgrep-change-to-wgrep-mode
        js2-refactor-hydra/js2r-extract-var-and-exit
        my/scrolldown
        ))
