;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-sexp
        org-self-insert-command
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-semicolon
        paredit-wrap-round
        smarter-move-beginning-of-line
        tab-to-tab-stop
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        eval-last-sexp
        my/scrolldown
        ))
